StatCan/aaw

.replace-hostname.sh, README.md, docs/en/1-Experiments/Kubeflow.md, docs/en/2-Publishing/R-Shiny.md, docs/en/Storage.md, docs/en/index.md, docs/fr/1-Experiences/Kubeflow.md, docs/fr/2-Publication/R-Shiny.md, docs/fr/Stockage.md, docs/fr/index.md
With permission from Rob & Brendan!
=> feat: add true hostname

docs/fr/Stockage.md
=> french translation

docs/en/Help.md
Clean up the Help Section to point to Slack.
=> feat(help): update the help section to direct users to slack.

.github/workflows/check.yml, .github/workflows/publish.yml, .spelling, README.md, docs/en/.spelling, docs/en/1-Experiments/Jupyter.md, docs/en/1-Experiments/Kubeflow.md, docs/en/2-Publishing/Custom.md, docs/en/2-Publishing/PowerBI.md, docs/en/2-Publishing/R-Shiny.md, docs/en/3-Pipelines/Kubeflow-Pipelines.md, docs/en/3-Pipelines/Pachyderm.md, docs/en/Collaboration.md, docs/en/Storage.md, docs/en/index.md, mkdocs-en.yml, mkdocs-fr.yml
Checks some common admonition issues and ensures content agrees with Prettier formatting.
This PR includes some formatting changes to eliminate Prettier warnings so that checks will pass on `master` and future branches. These formatting changes are using Prettier's defaults – the only aesthetic opinions they reflect would be those of the Prettier project maintainers. :stuck_out_tongue: 
Fixes #157
=> chore(ci): Add CI checks for consistent formatting 

.prettierignore, docs/en/.spelling, docs/en/3-Pipelines/Kubeflow-Pipelines.md
This is just @collinbrown95's PR but with Andrew's edits
=> K8s secrets

build-dev-docs.sh
=> fix: use daaas-topic instead of simple list

.spelling, docs/en/Storage.md
Quick update based on recent storage changes
=> Update Storage.md for new minio tenants

docs/en/4-Collaboration/Overview.md, docs/en/5-Storage/MinIO.md, docs/en/5-Storage/Overview.md, docs/en/index.md, mkdocs-en.yml
Adding a Storage overview document.
=> docs: Add overview documentation for storage

docs/fr/2-Publication/PowerBI.md
=> Revert "Translation of the changes made to the power BI doc"

docs/README.md, docs/en/3-Pipelines/Kubeflow-Pipelines.md, docs/en/4-Collaboration/Request-a-Namespace.md, docs/en/Help.md, docs/en/index.md, docs/fr/4-Collaboration/Demander-EspaceDeNom.md, docs/fr/Aide.md, docs/fr/Collaboration.md, docs/fr/index.md, docs/index.html, mkdocs-en.yml, mkdocs-fr.yml
=> update(docs): update broken links; Remove Covid-19 labels

docs/en/1-Experiments/Kubeflow.md, docs/en/1-Experiments/Selecting-an-Image.md
Some updates: including URL update, details about certain images (like conda environment torch in the PyTorch image), and heads-up on certain bugs that confuse users (can be removed when the bugs are fixed).
=> Update Documentation 1-Experiments

docs/fr/1-Experiences/Kubeflow.md, docs/fr/1-Experiences/Selectionner-une-Image.md
French Translation for https://github.com/StatCan/daaas/pull/807
=> Fix French Translation

.spelling, docs/en/5-Storage/MinIO.md, docs/fr/1-Experiences/Kubeflow.md, docs/fr/5-Stockage/MinIo.md
closes https://github.com/StatCan/daaas/issues/855
=> Fix minio links

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/onboarding-support-help.md
* Remove issue title prefixes that are covered by default issue labels
* Switch bold text to headers for accessibility
Resolves #948
=> Update issue templates

requirements.txt
hopefully fixes this comment by Stan 
https://github.com/StatCan/daaas/pull/1403#issuecomment-1309374638
=> fix(build): https://github.com/radude/mdx_truly_sane_lists/issues/9

docs/en/4-Collaboration/Geospatial-Analytical-Environment.md, docs/fr/4-Collaboration/Aperçu.md, docs/fr/4-Collaboration/Environnement-Analyse-Geospatiale.md, mkdocs-en.yml, mkdocs-fr.yml
Closes https://github.com/StatCan/daaas/issues/1487
=> Add GAE Documentation

docs/en/6-Gitlab/Gitlab.md, mkdocs-en.yml
Closes https://github.com/StatCan/daaas-private/issues/54
=> chore: update gitlab documentation

docs/en/6-Gitlab/Gitlab.md
add warning to users to not store creds
=> chore(gitlab readme): credential warning advice

docs/dev/getting started/jupyterlab.md
closes https://github.com/StatCan/daaas-private/issues/72
=> chore(jupyterlab concurrency): create basic file

.github/workflows/check.yml, docs/dev/getting started/jupyterlab.md, docs/en/3-Pipelines/Machine-Learning-Model-Cloud-Storage.md, docs/en/3-Pipelines/Machine-Learning-Model-Serving.md, docs/en/3-Pipelines/Machine-Learning-Training-Pipelines.md, docs/en/3-Pipelines/Machine-Learning.md, docs/en/3-Pipelines/Overview.md, docs/en/3-Pipelines/PaaS-Integration.md, docs/en/index.md
Some of the updated documentation pages were lost in the PR refactoring, I have added them back.
=> update 3-Pipelines Section: add missing files

docs/en/2-Publishing/R-Shiny.md
I added some information about running `shinyuieditor` on the AAW to the publishing section.
=> Add R Shiny UI Editor Information

docs/README.md, docs/en/4-Collaboration/Geospatial-Analytical-Environment.md
Update based on @Souheil-Yazji's feedback found here:
https://github.com/StatCan/daaas/pull/1608
=> Update wording in readme

docs/en/3-Pipelines/Machine-Learning-Model-Serving.md, docs/en/3-Pipelines/sklearn_iris_jsondata.ipynb, mkdocs-en.yml, overrides/main.html, package.json, requirements.txt, yarn.lock
I've added an example Jupyter Notebook for deploying a model as a service with Seldon Core.
=> Add new jupyter notebook abilities and example

docs/en/3-Pipelines/Machine-Learning-Training-Pipelines.md, docs/fr/3-Pipelines/Machine-Learning-Training-Pipelines.md
files changed:
- Machine-Learning-Training-Pipelines.md
=> update French: Machine-Learning-Training-Pipelines

docs/fr/3-Pipelines/PaaS-Integration.md
Files changed:
- PaaS-Integration.md
=> Update French: PaaS-Integration.md

docs/fr/2-Publication/R-Shiny.md
=> Update French: R-Shiny.md

docs/en/2-Publishing/Dash.md, docs/fr/2-Publication/Dash.md
=> Update french dash md

docs/fr/index.md
=> Update french index md

docs/en/5-Storage/AzureBlobStorage.md
closes https://github.com/StatCan/aaw/issues/1761
=> docs(fdi): update common storage docs

docs/en/5-Storage/AzureBlobStorage.md, docs/fr/5-Stockage/AzureBlobStorage.md
I added instructions for copying files into the correct sub-bucket, e.g. aaw-protected-b, aaw-unclassified.
=> update(AzureBlobStorage): add sub-bucket text

docs/en/1-Experiments/Jupyter.md, docs/en/1-Experiments/Kubeflow.md, mkdocs-en.yml
Part of https://github.com/StatCan/aaw/issues/1857
Fixing current code not building + test if link works
=> Fix the code not building

docs/en/2-Publishing/Dash.md, docs/en/2-Publishing/Datasette.md, docs/en/2-Publishing/R-Shiny.md, docs/en/3-Pipelines/Argo.md, docs/en/4-Collaboration/Overview.md, docs/en/6-Gitlab/Gitlab.md, docs/en/7-MLOps/Machine-Learning-Model-Cloud-Storage.md, docs/en/7-MLOps/Machine-Learning-Training-Pipelines.md, docs/en/7-MLOps/PaaS-Integration.md, docs/en/index.md
Closes https://github.com/StatCan/aaw/issues/787
=> Fix alts and css

mkdocs-en.yml
=> feat(ompp-docs): add ompp to mkdocs

docs/README.md, docs/dev/index.md
Cleanup and fix for getting-started link.
=> chore(docs): cleanup and fix broken link

docs/dev/getting-started/setup.md
I added info from https://confluenceb.statcan.ca/display/DAaaS/Kubernetes+documentation which may be useful for new developers.
=> update(setup.md): incorporate info from Confluence

docs/dev/features/object-storage/blobcsi.md
I added my instructions from https://github.com/StatCan/aaw/issues/1896 to the dev docs.
=> Add blob csi bucket details

docs/en/1-Experiments/Kubeflow.md
There is no longer a default namespace, users should just make sure that the correct one is selected.
=> docs(kf): update namespace selection section

docs/dev/getting-started/setup.md
For [BTIS-254](https://jirab.statcan.ca/browse/BTIS-254)
Remove the `kubectl` installation, as the suggested addition of `az aks install-cli` [installs kubectl and kubelogin](https://learn.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-install-cli)
=> Update onboarding docs
